<?php

namespace PW\NewsletterBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * NewsletterEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterEmailRepository extends DocumentRepository
{
    public function findUserIdsByNewsletter($newsletter)
    {
        $results = $this->createQueryBuilder()
            ->field('newsletter.$id')->equals(new \MongoId($newsletter->getId()))
            ->map('function() { emit(this.user.$id, 1); }')
            ->reduce('function(k, vals) {
                var sum = 0;

                for (var i in vals) {
                    sum += vals[i];
                }

                return sum;
            }')
            ->getQuery()->execute();

        $arr = array();
        foreach ($results as $r) {
            $arr[] = (string)$r['_id'];
        }

        return $arr;
    }
}