cybernox_amazon_web_services:
    key:                        %aws_key%
    secret:                     %aws_secret%
    account_id:                 %aws_account_id%
    enable_extensions:          []
    certificate_authority:      false
