doctrine_mongodb:
    connections:
        default:
            server: mongodb://%mongodb.default.host%:%mongodb.default.port%
            options:
                persist: true
    document_managers:
        default:
            connection:   default
            database:     %mongodb.default.name%
            logging:      %kernel.debug%
            auto_mapping: true
    auto_generate_proxy_classes:    true
    auto_generate_hydrator_classes: true
    default_document_manager:       default
    default_connection:             default
    default_database:               %mongodb.default.name%
