fos_rest:
    routing_loader:
        default_format: json
    view:
        view_response_listener: true
        formats:
            json: true
            xml: false
    body_listener: true
    format_listener: true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': HTTP_NOT_FOUND
            'Doctrine\ODM\MongoDB\DocumentNotFoundException':                HTTP_NOT_FOUND
            'Doctrine\ODM\MongoDB\LockException':                            HTTP_CONFLICT
            'Doctrine\ODM\MongoDB\MongoDBException':                         HTTP_INTERNAL_SERVER_ERROR
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
