parameters:
#    pw_feature.example.class: PW\FeatureBundle\Example

services:
#    pw_feature.example:
#        class: %pw_feature.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
